# Generated by Django 5.2 on 2025-05-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
